openapi: 3.0.3
info:
  version: 1.0.0
  title: Address management
  description: API related to management of Addresses.
paths:
  /addresses:
    get:
      tags:
        - Address
      summary: Fetches Addresses of User. Only Users of type client can fetch Restaurants
      operationId: getAddresses
      responses:
        '200':
          description: Resources successfully fetched.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AddressDetails'
        '403':
          description: User is not allowed to get Addresses.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
    post:
      tags:
        - Address
      summary: Creates an Addresses for an User. Only Users of type client are allowed to create addresses
      operationId: createAddress
      requestBody:
        description: Request body contains information related to new Address
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddressCreation'
        required: true
      responses:
        '201':
          description: Resource successfully created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddressCreationResponse'
        '400':
          description: Request body is invalid.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
        '403':
          description: User is not allowed to create Addresses.
          content:
            application/json:
              schema:
                $ref: 'common.yaml#/components/schemas/GenericApplicationError'
components:
  schemas:
    AddressDetails:
      type: object
      properties:
        id:
          description: Address's ID
          type: integer
          format: int64
          example: 100
        details:
          description: Address's details
          type: string
          example: Str. Strada Nr. 1
        latitude:
          description: Address's latitude
          type: number
          format: double
          example: 44.439663
        longitude:
          description: Address's longitude
          type: number
          format: double
          example: 26.096306
    AddressCreation:
      type: object
      required:
        - details
        - longitude
        - latitude
      properties:
        details:
          description: Address's details
          type: string
          maxLength: 100
          example: Str. Strada Nr. 1
        latitude:
          description: Address's latitude
          type: number
          format: double
          minimum: -90
          maximum: 90
          example: 44.439663
        longitude:
          description: Address's longitude
          type: number
          format: double
          minimum: -180
          maximum: 180
          example: 26.096306
    AddressCreationResponse:
      type: object
      properties:
        id:
          description: Address's ID
          type: integer
          format: int64
          example: 100
        details:
          description: Address's details
          type: string
          example: Str. Strada Nr. 1
        latitude:
          description: Address's latitude
          type: number
          format: double
          example: 44.439663
        longitude:
          description: Address's longitude
          type: number
          format: double
          example: 26.096306